core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('fujairah-dive-centre-about-us/',
         views.AboutUs.as_view(), name='about-us'),
    path('amazing-scuba-diving-contact-us/',
         views.ContactPageView.as_view(), name='contact-us'),
    path('sitemap.xml',
         views.SiteMapView.as_view(), name='sitemap'),
    path('update-contact-us-request/<int:pk>/',
         views.update_contact_us, name='update-contact-us')
]

divesandybeach/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
import os

urlpatterns = [
    path("admin/", admin.site.urls),
    # TODO: Create namespace for each app
    path("", include("diving.urls", namespace="diving")),
    path("", include("core.urls", namespace="core")),
    path("accounts/", include("allauth.urls")),
]


# if settings.DEBUG == False:
#     STATIC_ROOT = os.path.join(settings.BASE_DIR, "static")
#     urlpatterns += static(settings.STATIC_URL, document_root=STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# TODO: Customize admin check SDD urls.py
# TODO: Add url pattern for static and media root check SDD urls.py

diving/urls.py
from django.urls import path
from . import views
from . import upload_utils

app_name = 'diving'


urlpatterns = [
    path('fujairah-dive-sites/',
         views.DiveSiteListView.as_view(), name='dive-site-list'),
    path('fujairah-dive-sites/<slug>/',
         views.DiveSiteDetailView.as_view(), name='dive-site-detail'),
    path('padi-level/',
         views.PADICourseLevelListView.as_view(), name='course-level-list'),
    path('padi-level/<slug>/',
         views.PADICourseLevelDetailView.as_view(), name='course-level-detail'),
    path('padi-courses/',
         views.PADICourseListView.as_view(), name='padi-course-list'),
    path('padi-courses/<slug>/',
         views.PADICourseDetailView.as_view(), name='padi-course-detail'),
    path('dive-with-us/<slug>/',
         views.DiveDetailView.as_view(), name='fun-diving'),
    path('diving-prices/',
         views.PricesDetailView.as_view(), name='prices'),
    path('course-booking-request/',
         views.CourseBookingRequestView.as_view(), name='course-booking-request'),
    path('booking-request/',
         views.BookingRequestView.as_view(), name='booking-request'),
    path('upload-item-price/', upload_utils.UploadItemPrices.as_view(),
         name='upload-item-price'),
    path('upload-courses/', upload_utils.UploadCourses.as_view(),
         name='upload-courses'),
    path('upload-dive-sites/', upload_utils.UploadDiveSites.as_view(),
         name='upload-dive-sites'),
]

diving/forms.py
from django import forms
from django.forms.widgets import Select
from .models import (
    CourseBookingRequest,
    DiveBookingRequest,
    Course,
    CERT_LEVEL_CHOICES,
    TRIP_TIME_CHOICES,
    EQUIPMENT_CHOICES,
)
from tempus_dominus.widgets import DatePicker, TimePicker
from .widgets import KitSelectWidget, CertLevelSelectWidget

BLANK_CHOICE = [("", "Select cert level")]

CERT_CHOICE = (BLANK_CHOICE) + list(CERT_LEVEL_CHOICES)

# print(CERT_CHOICE)


class UploadCSVForm(forms.Form):
    csv_file = forms.FileField()


class CourseBookingRequestForm(forms.Form):
    COURSES = Course.objects.all()
    email = forms.EmailField(
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "Enter your email address"}
        )
    )
    try:
        course = forms.ChoiceField(
            choices=[(course.title, course.title) for course in list(COURSES)],
            widget=forms.Select(
                attrs={
                    "class": "form-control",
                    "placeholder": "Enter your email address",
                }
            ),
        )
    except Exception as e:
        print(e)
    date = forms.DateField(
        input_formats=["%d-%m-%Y"],
        widget=DatePicker(
            options={
                "icons": {
                    "next": "fas fa-chevron-right",
                    "previous": "fas fa-chevron-left",
                },
                "useCurrent": False,
            },
            attrs={"input_toggle": True, "input_group": False, "autocomplete": "off"},
        ),
    )

    message = forms.CharField(
        required=False,
        widget=forms.Textarea(
            attrs={"class": "form-control", "placeholder": "Send us a message"}
        ),
    )

    @property
    def __name__(self):
        return "CourseBookingForm"


class CourseBookingDivers(forms.Form):
    full_name = forms.CharField(
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "Enter divers full name"}
        )
    )

    @property
    def __name__(self):
        return "CourseBookingDivers"

    def __repr__(self):
        return "CourseBookingDivers"


class DiveBookingRequestForm(forms.Form):
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                "class": "form-control",
                "required": True,
                "placeholder": "Enter your email address",
            }
        )
    )

    date = forms.DateField(input_formats=["%d-%m-%Y"], required=True)

    message = forms.CharField(
        required=False,
        widget=forms.Textarea(
            attrs={"class": "form-control", "placeholder": "Send us a message"}
        ),
    )


class DiveBookingRequestDiverForm(forms.Form):
    full_name = forms.CharField(
        required=True,
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "required": True,
                "placeholder": "Enter diver full name",
            }
        ),
    )
    cert_level = forms.TypedChoiceField(
        required=True,
        choices=CERT_LEVEL_CHOICES,
        widget=CertLevelSelectWidget(attrs={"class": "form-control", "required": True}),
    )
    kit_required = forms.TypedChoiceField(
        required=True,
        choices=EQUIPMENT_CHOICES,
        widget=KitSelectWidget(attrs={"class": "form-control", "required": True}),
    )


class BoatDiveBookingRequestForm(DiveBookingRequestForm):
    boat_time = forms.ChoiceField(
        required=True,
        choices=TRIP_TIME_CHOICES,
        widget=forms.RadioSelect(attrs={"class": "custom-control-input"}),
    )

    @property
    def __name__(self):
        return "Boat Dive"


class ShoreDiveBookingRequestForm(DiveBookingRequestForm):
    shore_time = forms.CharField(required=True)
    shore = forms.CharField(
        required=False, widget=forms.HiddenInput(attrs={"value": "shore"})
    )

    @property
    def __name__(self):
        return "Shore Dive"

diving/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.utils.text import slugify
from django.views.generic import FormView
from django.views import View
from django.forms import formset_factory
from .models import (
    DiveSite,
    Category,
    Course,
    DiveTrip,
    ItemPrice,
    DiveBookingRequest,
    DiveBookingRequestDiver,
    CourseBookingRequest,
    CourseBookingExtraDivers,
)
from .forms import (
    CourseBookingDivers,
    UploadCSVForm,
    CourseBookingRequestForm,
    DiveBookingRequestForm,
    DiveBookingRequestDiverForm,
    BoatDiveBookingRequestForm,
    ShoreDiveBookingRequestForm,
)
from django.contrib import messages
from django.template.loader import render_to_string
from django.template import Context
from .email import StaffEmail, CustomerEmail, CourseStaffEmail


class DiveSiteListView(ListView):
    model = DiveSite
    context_object_name = "dive_sites"
    template_name = "diving/dive_site_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Fujairah Dive Sites"
        context[
            "seo_description"
        ] = "Check out our dive sites along the Fujairah coastline. Each site offering abundant marine life, ranging from ship wrecks to beautiful coral reef."
        context["seo_keywords"] = "Fujairah Dive Sites, Scuba Dive Fujairah"
        return context


class DiveSiteDetailView(DetailView):
    model = DiveSite
    context_object_name = "site"
    template_name = "diving/dive_site_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = context["object"].title
        context["seo_description"] = context["object"].seo_description
        context["seo_keywords"] = context["object"].seo_keywords
        return context


class PADICourseLevelListView(ListView):
    model = Category
    context_object_name = "course_levels"
    template_name = "diving/padi_course_level_list.html"


class PADICourseLevelDetailView(DetailView):
    model = Category
    context_object_name = "course_level"
    template_name = "diving/padi_course_level_detail.html"

    def get_context_data(self, **kwargs):
        courses = Course.objects.filter(level__title=kwargs["object"])
        context = super().get_context_data(**kwargs)
        context["courses"] = courses
        context["title"] = context["object"].title
        return context


class PADICourseListView(View):
    def get(self, request, *args, **kwargs):

        entry_level = Course.objects.filter(level__title="Entry Level")
        advanced_level = Course.objects.filter(level__title="Advanced Level")
        specialties = Course.objects.filter(level__title="Specialty Courses")
        pro_level = Course.objects.filter(level__title="Professional Level")
        tecrec_level = Course.objects.filter(level__title="TecRec Level")
        context = {
            "entry_level": entry_level,
            "advanced_level": advanced_level,
            "specialties": specialties,
            "pro_level": pro_level,
            "tecrec_level": tecrec_level,
            "title": "PADI Courses",
            "seo_description": "Full Range Of PADI Courses | PADI 5 Star IDC Resort |  From Entry Level Courses to PADI Profesional Programs, Sign Up With A PADI Instructor Today!",
        }

        return render(request, "diving/all_padi_courses.html", context=context)


class PADICourseDetailView(DetailView):
    model = Course
    template_name = "diving/padi_course_detail.html"
    context_object_name = "course"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = context["object"].title
        context["seo_description"] = context["object"].seo_description
        context["seo_keywords"] = context["object"].seo_keywords
        return context


class DiveDetailView(DetailView):
    model = DiveTrip
    template_name = "diving/fun_diving.html"
    context_object_name = "dive"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = context["object"].title
        context["seo_description"] = context["object"].seo_description
        context["seo_keywords"] = context["object"].seo_keywords
        price_filter = slugify(context["title"])
        context["prices"] = ItemPrice.objects.filter(trip_type=price_filter)

        return context


class PricesDetailView(TemplateView):
    template_name = "diving/prices.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["object"] = ItemPrice.objects.all()
        context["title"] = "Prices"
        context["categories"] = Category.objects.all()
        context["seo_descrition"] = (
            "Prices | Discover | Experience | PADI 5 Star IDC Resort | Daily Diving Trips, PADI Courses And Diving Equipment, Join Us For The The Best Diving In Fujairah!",
        )
        context["title"] = "Price List"
        return context


class BookingRequestView(View):
    def get(self, request, *args, **kwargs):
        referer = request.META.get("HTTP_REFERER")
        try:
            if referer.endswith("dive-snoopy-island/"):
                booking_form = ShoreDiveBookingRequestForm()
            else:
                booking_form = BoatDiveBookingRequestForm()
        except Exception:
            # Referer is none type, default to boat diving form
            booking_form = BoatDiveBookingRequestForm()

        diver_form = formset_factory(DiveBookingRequestDiverForm, validate_min=True)

        context = {
            "booking_form": booking_form,
            "diver_form": diver_form,
            "title": "Dive Booking Request",
            "heading": booking_form.__name__,
        }

        return render(request, "diving/booking_request.html", context=context)

    def post(self, request, *args, **kwargs):
        shore = request.POST.get("shore", None)
        if shore:
            booking_form = ShoreDiveBookingRequestForm(request.POST)
        else:
            booking_form = BoatDiveBookingRequestForm(request.POST)

        DiverFormSet = formset_factory(
            DiveBookingRequestDiverForm, validate_min=True, min_num=1
        )
        divers_formset = DiverFormSet(request.POST)

        context = {
            "booking_form": booking_form,
            "diver_form": divers_formset,
            "title": "Dive Booking Request",
            "heading": booking_form.__name__,
        }
        # print(booking_form)
        # print(divers_formset)

        if not divers_formset.is_valid() or not booking_form.is_valid():
            messages.info(request, "Sorry, your input was not valid, please try again")
            return render(request, "diving/booking_request.html", context=context)

        else:

            # Both forms are valid, construct email, only send email after successfull model creations
            divers = divers_formset.cleaned_data
            booking_info = booking_form.cleaned_data
            booking_info["subject"] = "Dive booking request"
            booking_info["dive_type"] = booking_form.__name__
            staff_email = StaffEmail(divers, booking_info)
            customer_email = CustomerEmail(divers, booking_info)

            # Set dive time based on dive trip type
            if booking_info["dive_type"] == "Boat Dive":
                time = booking_info["boat_time"]
            else:
                time = booking_info["shore_time"]

            # Create booking request
            booking_request = DiveBookingRequest(
                full_name=divers[0]["full_name"],
                email=booking_info["email"],
                trip_type=slugify(booking_info["dive_type"]),
                time=time,
                date=booking_info["date"],
                message=booking_info["message"],
            )
            booking_request.save()

            # Create diver and add them to booking request
            for diver in divers:
                new_diver = DiveBookingRequestDiver(
                    full_name=diver["full_name"],
                    cert_level=diver["cert_level"],
                    kit_required=diver["kit_required"],
                    dive_booking_query=booking_request,
                )
                new_diver.save()

            # New data saved to database, send emails
            staff_email.send()
            customer_email.send()

            messages.success(request, "Booking request success!")
            return render(request, "diving/booking_success.html")


class CourseBookingRequestView(View):
    def get(self, request, *args, **kwargs):
        # Build course title from refering URL
        url = request.META.get("HTTP_REFERER")
        last = url.split("/")[len(url.split("/")) - 2].split("-")
        last = " ".join(last).title()
        form = CourseBookingRequestForm(initial={"course": last})

        diver_form = formset_factory(CourseBookingDivers)
        context = {
            "form": form,
            "diver_form": diver_form,
            "title": "PADI Course Booking Request",
        }

        return render(request, "diving/course_booking_request.html", context=context)

    def post(self, request, *args, **kwargs):
        form = CourseBookingRequestForm(request.POST)
        DiverFormSet = formset_factory(
            CourseBookingDivers, validate_min=True, min_num=1
        )
        divers_formset = DiverFormSet(request.POST)
        # print(form)
        # print(divers_formset)

        context = {
            "form": form,
            "diver_form": divers_formset,
            "title": "PADI Course Booking Request",
        }

diving/templates/diving/boat_diving.html
{% extends 'core/base.html' %}

{% block extra_head %}
<style>
    .course-hero-image {
        background-image: url({{ dive.image.mobile_image.url }});
        background-repeat: no-repeat;
        background-size: cover;
        background-attachment: fixed;
        background-position: center;
    }


    @media (min-width: 400px) {
        .course-hero-image {
            background-image: url({{ dive.image.hero_image.url }});

        }
    }
</style>

{% endblock extra_head %}

{% block content %}

<section id="course-detail-heading">

    <div class="course-hero-overlay ">
        <div class="text-center title-text container">
            <h1 class="header">{{ dive.title }}</h1>
            <hr class="my-5 bg-light w-50 shadow-lg ml-auto mr-auto">
            <a href="{% url 'diving:booking-request' %}" class="btn btn-success btn-lg">Request a Booking!</a>
        </div>
    </div>
    <div class="course-hero-image">
    </div>

</section>

<!-- Pricing card -->
<section class="dive-trip-price-card-section bg-white py-5">
    <div class="container-lg">
        <h2 class="text-center pb-4 text-shadow">Pricing</h2>
        <div class="heading-underline"></div>

        <!-- Price row -->

        <!-- Tanks and Weights Card -->
        <div class="row mt-5">

            {% for price in prices %}

            <div class="col-md-4">
                <div class="price-card card bg-light shadow-lg text-center mb-5">
                    {% if price.dive_trip_equipment == 'Full Kit' %}
                    <div class="popular-ribbon">Popular</div>

                    {% endif %}
                    <div class="card-header text-center bg-dark pt-5 ">
                        <h4 class="card-title-text">{{ price.dive_trip_equipment }}</h4>
                        <div class="heading-underline"></div>
                    </div>
                    <div class="card-body  py-5">
                        <h1><b>{{ price.price }} </b><small class="text-muted">AED</small></h1>
                    </div>
                    <ul class="list-group list-group-flush bg-light">
                        <li class="list-group-item bg-light"><i class="fas fa-check text-success mx-2"></i>
                            Tanks and Weights
                        </li>
                        <li class="list-group-item bg-light"><i class="fas fa-check text-success mx-2"></i>
                            Boat Trip
                        </li>
                        <li class="list-group-item bg-light"><i class="fas fa-check text-success mx-2"></i> Incl
                            Awesome Dives
                        </li>
                    </ul>

                </div>
            </div>

            {% endfor %}

            <!-- End Tanks and weights Card -->

        </div>
    </div>
    <!-- End course price card row -->
</section>


<!--  -->

<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-sm-10">
            <div id="course-info-rows">

                <!-- Course Overview row -->
                <div class="row">
                    <div class="col-md-6">
                        <h3 class="text-center pb-4">Course Overview</h3>
                        <div class="heading-underline"></div>
                        <ul class="list-group list-group-flush bg-transparent">
                            <li class="list-group-item"><b>Minimum Age: </b> {{ course.min_age }}</li>
                            <li class="list-group-item"><b>Duration: </b> {{ course.duration }}</li>
                            {% if course.ocean_dives == True %}
                            <li class="list-group-item"><b>Number of Ocean Dives: </b>{{ course.num_ocean_dives }}
                            </li>
                            {% endif %}
                            {% if course.pool_dives == True %}
                            <li class="list-group-item"><b>Number of Pool Dives: </b>{{ course.num_pool_dives }}
                            </li>
                            {% endif %}
                            <li class="list-group-item"><b>Qualified To: </b>{{ course.qualified_to }} min</li>
                        </ul>
                    </div>
                    <div class="col-md-6 text-center order-md-1">
                        <div class="course-info-img"
                            style="background-image: url({{ course.e_learning_info.image.url }});">
                        </div>
                    </div>
                </div>
                <!-- End Course Overview row -->

                <!-- Course Info row -->
                <div class="row ">
                    <div class="col-md-6 order-md-2">
                        <h3 class="text-center pb-4">Course Info</h3>
                        <div class="heading-underline"></div>
                        <p>{{ course.description | linebreaks }}</p>
                    </div>
                    <div class="col-md-6 text-center order-md-1">
                        <div class="course-info-img"
                            style="background-image: url({{ course.e_learning_info.image.url }});">
                        </div>
                    </div>
                </div>
                <!-- End Course Info row -->

                <!-- E-Learning info row -->
                {% if course.e_learning_info %}
                <div class="row ">
                    <div class="col-md-6 text-center order-md-2">
                        <h3 class="text-center pb-4">{{ course.e_learning_info.heading }}</h3>
                        <div class="heading-underline"></div>
                        <p>{{ course.e_learning_info.text }}</p>
                        <div>

                            <a target="blank" href="{{ course.e_learning_link }}" class="btn btn-info">Sign up for your
                                E-Learning</a>
                        </div>
                    </div>
                    <div class="col-md-6 text-center order-md-1">
                        <div class="course-info-img"
                            style="background-image: url({{ course.e_learning_info.image.url }});">
                        </div>
                    </div>
                </div>
                {% endif %}
                <!-- End E-Learning info row -->

                <!-- Book Learning info row -->
                {% if course.book_learning_info %}
                <div class="row ">
                    <div class="col-md-6 text-center order-md-1">
                        <h3 class="text-center pb-4">{{ course.book_learning_info.heading }}</h3>
                        <div class="heading-underline"></div>
                        <p>{{ course.book_learning_info.text }}</p>
                    </div>
                    <div class="col-md-6 text-center order-md-2">
                        <div class="course-info-img"
                            style="background-image: url({{ course.book_learning_info.image.url }});">
                        </div>
                    </div>
                </div>
                {% endif %}
                <!-- End Book Learning info row -->

                <!-- Pool Dives info row -->
                {% if course.pool_info %}
                <div class="row ">
                    <div class="col-md-6 text-center order-md-2">
                        <h3 class="text-center pb-4">{{ course.pool_info.heading }}</h3>
                        <div class="heading-underline"></div>
                        <p>{{ course.pool_info.text }}</p>
                    </div>
                    <div class="col-md-6 text-center order-md-1">
                        <div class="course-info-img" style="background-image: url({{ course.pool_info.image.url }});">
                        </div>
                    </div>
                </div>
                {% endif %}
                <!-- End Pool Dives info row -->

                <!-- Ocean Dives info row -->
                {% if course.ocean_info %}
                <div class="row ">
                    <div class="col-md-6 text-center">
                        <h3 class="text-center pb-4">{{ course.ocean_info.heading }}</h3>
                        <div class="heading-underline"></div>
                        <p>{{ course.ocean_info.text }}</p>
                    </div>
                    <div class="col-md-6 text-center">
                        <div class="course-info-img" style="background-image: url({{ course.ocean_info.image.url }});">
                        </div>
                    </div>
                </div>
                {% endif %}
                <!-- End Ocean Dives info row -->

            </div>

        </div>
    </div>





    <!-- Pool Dives info row -->
    <div class="row my-5">
        <div class="col-md-6">
            <!--  -->
        </div>
    </div>
    <!-- End Pool Dives info row -->

    <!-- Ocean Dives info row -->
    <div class="row my-5">
        <div class="col-md-6">
            <!--  -->
        </div>
    </div>
    <!-- End Ocean Dives info row -->

</div>


{% endblock content %}

diving/templates/diving/dive_site_detail.html
{% extends 'core/base.html' %}


{% block content %}
<section id="sites-heading">

    <div class="hero-bg">
        <div class="container title-text">
            <h1 class="header">{{ site.title }}</h1>
            <hr class="my-5 bg-light w-50 shadow-lg">
            <div class="os-animation text-center" data-animation="fadeInUp" data-delay="0.6s">
                <a class="btn btn-success text-1 font-weight-semibold text-uppercase px-5 btn-py-2 mb-3"
                    href="{% url 'diving:booking-request' %}">Request a booking</a>
            </div>
        </div>
    </div>

</section>



<div class="container content-section my-3 h-100">
    <div class="row pt-3 ">
        <div class="col-12 col-md-8 order-2 order-md-1">
            <h3 class="text-center">Site Description</h3>
            <div class="heading-underline"></div>
            <p>{{ site.info | linebreaks }}</p>
        </div>

        <div class="col-12 mb-5 col-md-4 order-md-2">
            <div>
                <div class="card">
                    <h3 class="text-center pt-5 pt-md-0 pb-2">Site Info</h3>
                    <div class="heading-underline"></div>
                    <ul class="site-info list-group list-group-flush">
                        <li class="list-group-item"><b>Minimum Diver Level: </b>{{ site.min_diver_level }}</li>
                        <li class="list-group-item"><b>Depth: </b>{{ site.depth }}m</li>
                        <li class="list-group-item"><b>Dive Site Type: </b>{{ site.site_type }}</li>
                        <li class="list-group-item"><b>Dive Time: </b>{{ site.dive_time }} Min</li>
                        <li class="list-group-item"><b>Distance to Site: </b> {{ site.distance }} Min</li>
                        <li class="list-group-item"><b>What can we see?: </b>
                            {% for marine_life in site.marine_life.all %}
                            {{ marine_life }},
                            {% endfor %}
                        </li>
                    </ul>
                </div>

            </div>
        </div>

    </div>
</div>

<div class="container">
    <div class="row my-5 justify-content-center">
        <div class="col-12 text-center">
            <h3 class="mb-3">Dive Site Map</h3>
            <div class="heading-underline"></div>
            <div class="divesite-map">
                <img src="{{ site.map_image.url }}" id="img" class="divesite-map-image__img" alt="{{ site.title }}">
            </div>
        </div>


    </div>

</div>

<!-- booking button -->
<section class="bg-white py-5">
    <div class="container text-center">
        <h3 class="text-shadow pb- wow fadeInUp">Request a Booking!</h3>
        <div class="heading-underline wow fadeIn"></div>
        <p class=" pb-4">Send us a message to check availability for our next boat diving trip</p>
        <a href="{% url 'diving:booking-request' %}" class="btn btn-success btn-lg wow fadeIn">Send your
            Request</a>
    </div>
</section>

<!-- end booking button -->


{% endblock content %}

diving/templates/diving/divesites_changelist.html
{% extends 'admin/change_list.html' %}

{% block object-tools %}
<div class="mb-3" style="margin-bottom:20px;">
    <a href="{% url 'diving:upload-dive-sites' %}">Import CSV</a>
    <br>
</div>

{{ block.super }}
{% endblock %}

diving/templates/diving/itemsprices_changelist.html
{% extends 'admin/change_list.html' %}

{% block object-tools %}
<div class="mb-3" style="margin-bottom:20px;">
    <a href="{% url 'diving:upload-item-price' %}">Import CSV</a>
    <br>
</div>

{{ block.super }}
{% endblock %}

diving/templates/diving/padi_course_level_detail.html
{% extends 'core/base.html' %}


{% load static %}

{% block content %}
<!-- <section id="sites-heading">
    <div class="jumbrotron-fluid">
        <div class="container">
            <h1 class="display-3 mt-4">Pro Level Courses</h1>
            <hr>
            <a href="{% url 'diving:course-level-list' %}">course levels</a>
            <a href="">></a>
            <a href="{% url 'diving:course-level-detail' course_level.slug %}">{{ course_level.title }}</a>
            <p class="lead">Check out all our pro level courses</p>
        </div>

    </div>
</section> -->

<section id="sites-heading">

    <div class="hero-bg">
        <div class="container title-text">
            <h1 class=" header">{{ course_level.title }}</h1>
            <hr class="my-5 bg-light w-50 shadow-lg">
            <p class="lead">{{ course_level.intro }}</p>
        </div>
    </div>

</section>

<div class="container">
    <div class="row">
        {% for course in courses %}

        <div class="col-md-4">
            <div class="card my-5">
                <a href="{{ course.get_absolute_url }}"><img src="{{ course.image.medium_image.url }}"
                        class="card-img-top cd" alt="..."></a>
                <div class="card-body">
                    <a href="{{ course.get_absolute_url }}">
                        <h4 class="card-title text-center">{{ course.title }}</h4>
                        <div class="heading-underline"></div>
                    </a>
                    <ul class="list-group list-group-flush my-4">
                        <li class="list-group-item"><b>Title: </b>{{ course.title }}</li>
                        {%if course.price_e_learning %}
                        <li class="list-group-item"><b>E-learning Price: </b>{{ course.price_e_learning }}</li>
                        {% endif %}
                        <li class="list-group-item"><b>Book Price: </b>{{ course.price_book }}</li>
                    </ul>
                    <a href="{{ course.get_absolute_url }}" class="btn btn-primary btn-block">More
                        Info</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock content %}