core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('fujairah-dive-centre-about-us/',
         views.AboutUs.as_view(), name='about-us'),
    path('amazing-scuba-diving-contact-us/',
         views.ContactPageView.as_view(), name='contact-us'),
    path('sitemap.xml',
         views.SiteMapView.as_view(), name='sitemap'),
    path('update-contact-us-request/<int:pk>/',
         views.update_contact_us, name='update-contact-us')
]

divesandybeach/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
import os

urlpatterns = [
    path("admin/", admin.site.urls),
    # TODO: Create namespace for each app
    path("", include("diving.urls", namespace="diving")),
    path("", include("core.urls", namespace="core")),
    path("accounts/", include("allauth.urls")),
]


# if settings.DEBUG == False:
#     STATIC_ROOT = os.path.join(settings.BASE_DIR, "static")
#     urlpatterns += static(settings.STATIC_URL, document_root=STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# TODO: Customize admin check SDD urls.py
# TODO: Add url pattern for static and media root check SDD urls.py

diving/urls.py
from django.urls import path
from . import views
from . import upload_utils

app_name = 'diving'


urlpatterns = [
    path('fujairah-dive-sites/',
         views.DiveSiteListView.as_view(), name='dive-site-list'),
    path('fujairah-dive-sites/<slug>/',
         views.DiveSiteDetailView.as_view(), name='dive-site-detail'),
    path('padi-level/',
         views.PADICourseLevelListView.as_view(), name='course-level-list'),
    path('padi-level/<slug>/',
         views.PADICourseLevelDetailView.as_view(), name='course-level-detail'),
    path('padi-courses/',
         views.PADICourseListView.as_view(), name='padi-course-list'),
    path('padi-courses/<slug>/',
         views.PADICourseDetailView.as_view(), name='padi-course-detail'),
    path('dive-with-us/<slug>/',
         views.DiveDetailView.as_view(), name='fun-diving'),
    path('diving-prices/',
         views.PricesDetailView.as_view(), name='prices'),
    path('course-booking-request/',
         views.CourseBookingRequestView.as_view(), name='course-booking-request'),
    path('booking-request/',
         views.BookingRequestView.as_view(), name='booking-request'),
    path('upload-item-price/', upload_utils.UploadItemPrices.as_view(),
         name='upload-item-price'),
    path('upload-courses/', upload_utils.UploadCourses.as_view(),
         name='upload-courses'),
    path('upload-dive-sites/', upload_utils.UploadDiveSites.as_view(),
         name='upload-dive-sites'),
]

core/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

CERT_LEVEL_CHOICES = (
    ('OW', "Open Water"),
    ('AOW', "Advanced Open Water"),
    ('RD', "Rescue Diver"),
    ('DM', "Dive Master"),
    ('INST', "Instructor"),
)


class User(AbstractUser):
    USER_NAME = 'email'
    cert_level = models.CharField(max_length=255, choices=CERT_LEVEL_CHOICES)


class ContactUsRequest(models.Model):
    full_name = models.CharField(max_length=255)
    email = models.EmailField()
    message = models.TextField(null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    responded = models.BooleanField(default=False)

    def __str__(self):
        return self.email + ' - ' + self.date.strftime('%y%m%D')

    class Meta:
        verbose_name_plural = 'Contact Queries'

core/forms.py
from django import forms
from django.forms import ModelForm, Form
from .models import ContactUsRequest
from snowpenguin.django.recaptcha3.fields import ReCaptchaField


class ContactForm(Form):
    full_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter divers full name'}))
    email = forms.EmailField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter your email address'}))
    message = forms.CharField(required=False, widget=forms.Textarea(
        attrs={'class': 'form-control', 'placeholder': 'Send us a message'}))
    captcha = ReCaptchaField()

core/views.py
from django.shortcuts import render, reverse
from django.urls import reverse_lazy
from django.views.generic import TemplateView
from django.views import View
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt
from .forms import ContactForm
from django.http import HttpResponse
from django.contrib.messages.views import SuccessMessageMixin
from django.template.loader import render_to_string
from django.core.mail import send_mail
from diving.email import CustomerEmail
from .models import ContactUsRequest


class Home(TemplateView):
    template_name = 'core/index.html'


class AboutUs(TemplateView):
    template_name = 'core/about.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'About Us'
        context['seo_description'] = 'About Us | PADI 5 Star IDC Resort | Daily diving trips, PADI courses and diving equipment, join us for the best diving in Fujairah!'
        return context


class ContactPageView(View):

    def get(self, request, *args, **kwargs):
        form = ContactForm()
        context = {'title': 'Contact Us',
                   'form': form}

        return render(request, 'core/contact.html', context=context)

    def post(self, request, *args, **kwargs):
        info = ContactForm(request.POST)
        if not info.is_valid():
            # messages.info(
            #     request, 'Sorry, your input was not valid, please try again')
            return render(request, 'core/contact.html', context={'form': info})
        else:
            name = info.cleaned_data['full_name']
            email = info.cleaned_data['email']
            message = info.cleaned_data['message']

            # Create contact request for the database
            contact_request = ContactUsRequest.objects.create(
                full_name=name,
                email=email,
                message=message
            )

            context = {
                'full_name': name,
                'email': email,
                'message': message,
                'url': request.build_absolute_uri(reverse('core:update-contact-us', args=(contact_request.id, ))),
                'contact': True,
                'contact_subject': 'Contact Us'
            }

            # Send customer email
            customer_email = CustomerEmail([], context)
            customer_email.send()
            contact_request.save()

            # Send email with message to staff
            msg = render_to_string(
                'diving/email/contact_us_request.html', context=context)
            send_mail('Contact Us', msg, 'info@divesandybeach.com',
                      ['info@divesandybeach.com'], html_message=msg)

            # messages.info(request, 'Thank you for contacting us!')
            return render(request, 'diving/booking_success.html')


class SiteMapView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'core/sitemap.xml', content_type="application/xhtml+xml")


@csrf_exempt
def update_contact_us(request, pk):
    if request.method == 'GET':
        data = request.POST
        contact_request = ContactUsRequest.objects.get(pk=pk)
        contact_request.responded = True
        contact_request.save()
        return HttpResponse(status=200)
    else:
        return HttpResponse('Bad request', status=400)


""" TODO
- update-contact-us view, redirect on successful update of model
 """

core/templates/core/contact_thank_you.html
{% extends 'core/base.html' %}


{% block content %}
<section id="sites-heading">

    <div class="hero-bg">
        <div class="container title-text">
            <h1 class=" header">Thank you for Contacting us</h1>
            <hr class="my-5 bg-light w-50 shadow-lg">
        </div>
    </div>

</section>



<div class="container content-section my-3 h-100">
    <div class="row pt-3">
        <div class="col-md-6">
            <div>
                <h3 class="text-center pb-2">Site Info</h3>
                <ul class="site-info list-group list-group-flush">
                    <li class="list-group-item"><b>Minimum Level: </b>{{ site.min_diver_level }}</li>
                    <li class="list-group-item"><b>Depth: </b>{{ site.depth }}m</li>
                    <li class="list-group-item"><b>Dive Site Type: </b>{{ site.site_type }}</li>
                    <li class="list-group-item"><b>Dive Time: </b>{{ site.dive_time }} Min</li>
                    <li class="list-group-item"><b>Distance to Site: </b> {{ site.distance }} Min</li>
                    <li class="list-group-item"><b>What can we see?: </b>
                        {% for marine_life in site.marine_life.all %}
                        {{ marine_life }},
                        {% endfor %}
                    </li>
                </ul>
            </div>

            <div class="text-center mb-5">
                <h3 class="pt-5 pb-4">Request a Booking!</h3>
                <a href="#" class="btn btn-success btn-lg">Send your Request</a>
            </div>

        </div>
        <div class="col-md-6">
            <h3 class="text-center">Site Description</h3>
            <hr>
            <p>{{ site.info | linebreaks }}</p>
        </div>
    </div>
</div>

<div class="container">
    <div class="row my-5">
        <div class="col-md-12 text-center">
            <h3 class="mb-3">Dive Site Map</h3>
            <div class="heading-underline"></div>
            <div class="divesite-map">
                <img src="{{ site.image.url }}" id="img" class="divesite-map-image__img" alt="...">
            </div>
        </div>

    </div>
</div>


{% endblock content %}

core/templates/core/footer.html
{% load static %}

<footer>
    <div class="row justify-content-center footer-row">
        <div class="col-md-10">
            <div class="row py-3 text-center justify-content-center">
                <div class="col-md-6 col-xl-3 my-3">
                    <a href="{% url 'core:home' %}"><img
                            src="{% static 'core/img/SBDC Logo and text Hotel all white.png' %}" class="bottom-logo"
                            alt=""></a>
                </div>

                <div class="col-md-6 col-xl-3 my-3">
                    <p>Connect With Us</p>
                    <hr>
                    <ul class="list-unstyled connect text-large">
                        <li class="list-group-item"><i class="fas fa-phone"></i>+971 50 206 2440</li>
                        <li class="list-group-item">info@divesandybeach.com</li>
                        <li class="list-group-item social"><a target="blank"
                                href="https://www.facebook.com/divesandybeach" <i
                                class="fab fa-facebook-square mx-3 fa-2x"></i></a><a target="blank"
                                href="https://www.instagram.com/divesandybeach"><i
                                    class="fab fa-instagram fa-2x"></i></a></li>
                    </ul>

                </div>


                <div class="col-md-6 col-xl-3 footer-links my-3">
                    <p>Site Links</p>
                    <hr>
                    <ul class="list-group">
                        <li class="list-group-item"><a href="{% url 'diving:dive-site-list' %}">Dive Sites</a></li>
                        <li class="list-group-item"><a href="{% url 'diving:prices' %}">Prices</a></li>
                        <li class="list-group-item"><a href="{% url 'core:contact-us' %}">Contact Us</a></li>
                    </ul>
                </div>

                <div class="col-md-6 col-xl-3 footer-links my-3">
                    <p>Useful Links</p>
                    <hr>
                    <ul class="list-group">
                        <li class="list-group-item"><a target="blank" href="https://www.padi.com/">PADI.com</a></li>
                        <li class="list-group-item"><a target="blank"
                                href="https://www.tide-forecast.com/locations/Khor-Al-Fakkan/forecasts/latest/six_day">Tide
                                Forecast</a></li>
                        <li class="list-group-item"><a target="blank" href="http://sandybeachhotel.ae/">Sandy Beach
                                Hotel & Resort</a>
                        </li>
                    </ul>
                </div>


            </div> <!-- End Row -->
            <hr>
            <p class="text-center">Sandy Beach Dive Centre &copy; 2023 </p>
        </div> <!-- End col 10 -->
    </div>
</footer>

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block content %}

{% load static %}


<div role="main" class="main">

    <!-- Start of Landing Page Main Picture -->

    <div class="landing-fh-image">
        <div class="container d-flex h-100 justify-content-center">
            <div class="row align-content-center">
                <div class="col text-center title-text">
                    <div class="animated fadeInUp">
                        <h1 class="title-text mb-5">Scuba Diving in Fujairah</h1> <!-- PHP WP FUNCTION PAGE TITLE -->
                    </div>
                    <div class="animated fadeInUp ">
                        <p class="mb-5 mx-auto">Are you a certified diver? We would love to take you on your next
                            dive in
                            Fujairah. Click the button below to sign up for your next dive trip</p>
                    </div>
                    <div class="animated fadeInUp">
                        <a class="btn btn-primary btn-lg" href="{% url 'diving:booking-request' %}">Request a
                            booking</a>
                    </div>
                </div>
            </div>
        </div> <!-- End Container -->
        <div class="landing-dark-overlay"></div>
    </div>

    <!-- End of landing page main picture -->

    <!-- Start What we Specialize in Section -->

    <section id="specialize" class="py-5">
        <div class="container-lg">
            <div class="row px-2 justify-content-center mb-4">
                <div>
                    <h1 class="header mb-4 text-dark text-center text-shadow">We Specialize In</h1>
                    <div class="heading-underline"></div>
                </div>


            </div>
            <div class="card-deck text-center">

                <div class="card mb-5 wow fadeInLeft">
                    <a href="{% url 'diving:fun-diving' 'fujairah-boat-dive' %}"><img class="card-img-top"
                            src="{% static 'core/img/Pierre DSD Snoopy.jpg' %}" alt="Boat Diving"></a>
                    <div class="card-body">
                        <h2 class="card-title">Boat Diving</h2>
                        <p class="px-2">Daily double tank dive trips to our favorite dive sites along the Fujairah
                            coastline. You can check the Fujairah scuba diving cost on our prices page or our dive sites
                            on our dive sites page.</p>
                    </div>
                    <div class="card-footer border-top-0 bg-white">

                        <a href="{% url 'diving:fun-diving' 'fujairah-boat-dive' %}"
                            class="btn btn-success btn-lg my-3 mr-3">Learn More <i class="fa fa-chevron-right"
                                aria-hidden="true"></i></a>

                    </div>
                </div>

                <div class="card mb-5 wow fadeInUp">
                    <a href="{% url 'diving:fun-diving' 'dive-snoopy-island' %}"><img class="card-img-top"
                            src="{% static 'core/img/sqr- Co.jpg' %}" alt="Shore Diving"></a>
                    <div class="card-body">
                        <h2 class="card-title">Shore Diving</h2>
                        <p class="card-text">Dive around the famous Snoopy Island. The island is just a shore dive away,
                            scuba diving is near you in Fujairah, bring a buddy, set up your diving equipment and head
                            out to see the amazing marine life!</p>

                    </div>
                    <div class="card-footer border-top-0 bg-white">
                        <a href="{% url 'diving:fun-diving' 'dive-snoopy-island' %}"
                            class="btn btn-success btn-lg my-3 mr-3">Learn More <i class="fa fa-chevron-right"
                                aria-hidden="true"></i></a>

                    </div>
                </div>

                <div class="card mb-5 wow fadeInRight">
                    <a href="{% url 'diving:padi-course-list' %}"><img class="card-img-top"
                            src="{% static 'core/img/Lady in The Sand.jpg' %}" alt="PADI Courses"></a>
                    <div class="card-body">
                        <h2 class="card-title">PADI Courses</h2>
                        <p class="card-text">We are a leading PADI IDC Centre offering a full range of courses from
                            Beginner to Professional levels. Sign up for your e-learning or speak to one of our PADI
                            Instructors
                            for more information.</p>
                    </div>
                    <div class="card-footer border-top-0 bg-white">
                        <a href="{% url 'diving:padi-course-list' %}" class="btn btn-success btn-lg my-3 mr-3">Learn
                            More <i class="fa fa-chevron-right" aria-hidden="true"></i></a>
                    </div>
                </div>


            </div>
        </div>
</div> <!-- End of Row -->

</section>

<!-- End of What We Specialize in Section -->

<!-- Start of Dive Sites Call to Action -->
<section id="divesitecta">

    <div class="dive-site-cta-hero-bg">
        <div class="container ">
            <h2 class="title-text">Dive Sites</h2>
            <p class="my-4 text-lg-10">From wrecks to reefs, we dive it all! We know the best dive sites for spotting
                Blacktip Reef
                sharks, Turtles, Seahorses, Sting Rays, and if you’re lucky maybe even a Whaleshark! Check out all our
                sites to learn more about the dive sites along the Fujairah coastline.</p>
            <a class="btn btn-lg btn-success" href="{% url 'diving:dive-site-list' %}">Check Them Out <i
                    class="fa fa-chevron-right" aria-hidden="true"></i></a>
        </div>
    </div>

</section>



<!-- End of Dive Sites call to action -->

<!-- Our characterists Section -->

<section id="charateristics">
    <div class="container">
        <div class="row  align-content-center justify-content-center my-5">

            <div class="col-md-6 col-lg-4 text-center my-md-5 px-4">
                <div class="wow fadeIn">
                    <i class="fas fa-fish fa-4x mb-4"></i>
                    <h4>Marine Life</h4>
                    <hr class="w-50 mx-auto">
                    <p>Fujairah has the most abundant and diverse marine life in the UAE. Our dive sites are not
                        further
                        than 30 minutes drive by boat, they range from 12m - 30m, there are hard corals and soft corals
                        and a
                        variety
                        of Indian ocean reef fishes, Whalesharks also frequent our shores.</p>
                </div>
            </div>

            <div class="col-md-6 col-lg-4 text-center my-md-5 px-4">
                <div class="wow fadeIn">
                    <i class="fas fa-umbrella-beach fa-4x mb-4"></i>
                    <h5>Located On The Beach</h5>
                    <hr class="w-50 mx-auto">
                    <p>Located directly in front of Snoopy Island allows us the best shore diving in the UAE. We
                        are
                        based in Sandy Beach hotel and Resort on the east coast of the UAE, the Fujairah coastline
                        offers the best diving in the UAE with temperate to warm waters all year around.</p>
                </div>
            </div>



            <div class="col-md-6 col-lg-4 text-center my-md-5 px-4">
                <div class="wow fadeIn">
                    <i class="fas fa-ship fa-4x mb-4"></i>
                    <h4>Boat Diving</h4>
                    <hr class="w-50 mx-auto">
                    <p>We run two boat trips per day, our boat is dedicated for diving with all safety equipment
                        and
                        kit racks. Our boats cater for no more than 12 divers, each dive trip has a dedicated
                        Divemaster on board who will guide you around our favorite dive sites.</p>
                </div>
            </div>


            <div class="col-md-6 col-lg-4 text-center my-md-5 px-4">
                <div class="wow fadeIn">
                    <i class="fas fa-users fa-4x mb-4"></i>
                    <h4>Family Environment</h4>
                    <hr class="w-50 mx-auto">
                    <p>Being based in Sandy Beach Hotel and Resort provides our divers with the perfect family
                        environment. Divers can head out for a day of diving on the boat or from shore while their
                        families can enjoy the swimming pool or beach facilities.</p>
                </div>
            </div>

            <div class="col-md-6 col-lg-4 text-center my-md-5 px-4">
                <div class="wow fadeIn">
                    <i class="fas fa-star fa-4x mb-4"></i>
                    <h4>Service Excellence</h4>
                    <hr class="w-50 mx-auto">
                    <p>Being a 5-star PADI IDC Centre means we adhere to the latest training standards and teaching
                        techniques. All our dive guides and Instructors are PADI professionals who care for individual
                        diver needs and the environment.</p>
                </div>
            </div>

            <div class="col-md-6 col-lg-4 wow fadeIn text-center my-3 my-md-5 px-4">
                <div class="wow fadeIn">
                    <i class="fas fa-cogs fa-4x mb-4"></i>
                    <h4>Serviced Equipment</h4>
                    <hr class="w-50 mx-auto">
                    <p>We offer a full range of scuba diving equipment for rental, we also offer technical diving
                        facilities
                        with
                        Nitrox and oxygen. All of our equipment is regularly serviced and maintained to ensure diver
                        comfort and safety.</p>
                </div>
            </div>

        </div> <!-- End of Row -->
    </div> <!-- End of container fluid -->
</section>

<!-- End Our characterists Section -->

<!-- Start Partners section -->

<section id="partners">
    <div class="jumbotron">
        <div class="container-fluid text-center">

            <div class="os-animation" data-animation="fadeInUp" data-delay="0.1s">
                <h1 class="header mb-4 text-dark">Our Partners</h1>
                <div class="heading-underline"></div>
            </div>

            <div class="row">
                <div class="col-6 col-md-3 col-lg-2 partner-logo d-flex align-items-center mb-5 justify-content-center">
                    <a target="blank" href="https://www.padi.com/"><img
                            src="{% static 'core/img/logo/Partner-Logo_0005_PADI.png' %}" alt="PADI Logo"></a>
                </div>

                <div
                    class="col-6 col-md-3 col-lg-2 partner-logo  d-flex align-items-center mb-5 justify-content-center">
                    <a target="blank" href="https://www.padi.com/technical-courses"><img
                            src="{% static 'core/img/logo/Partner-Logo_0002_PADI-Tec-Rec.png' %}" alt="PADI Logo"></a>
                </div>

                <div
                    class="col-6 col-md-3 col-lg-2 partner-logo  d-flex align-items-center mb-5 justify-content-center">
                    <a target="blank" href="https://www.scubapro.com/"><img
                            src="{% static 'core/img/logo/Partner-Logo_0000_ScubaPro.png' %}" alt="PADI Logo"></a>
                </div>

                <div
                    class="col-6 col-md-3 col-lg-2 partner-logo  d-flex align-items-center mb-5 justify-content-center">
                    <a target="blank" href="https://www.projectaware.org/"><img
                            src="{% static 'core/img/logo/Partner-Logo_0004_Project-AWARE.png' %}" alt="PADI Logo"></a>
                </div>

                <div
                    class="col-6 col-md-3 col-lg-2 partner-logo  d-flex align-items-center mb-5 justify-content-center">
                    <a target="blank" href="https://www.emiratesdiving.com/"><img
                            src="{% static 'core/img/logo/Partner-Logo_0006_EDA.png' %}" alt="PADI Logo"></a>
                </div>

                <div
                    class="col-6 col-md-3 col-lg-2 partner-logo  d-flex align-items-center mb-5 justify-content-center">
                    <a target="blank" href="https://www.mares.com/en-IC/home/"><img
                            src="{% static 'core/img/logo/Partner-Logo_0001_Mares.png' %}" alt="PADI Logo"></a>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- End partners section -->



{% endblock content %}

core/templates/core/navbar.html
{% load static %}

<!-- <div class="top-scroll">
    <a href="#"><i class="fas fa-arrow-up fa-1.5x"></i></a>
</div> -->
<header>
    <div class="mobile-div">
        <div class="mobile-next-to"></div>
        <div class="mobile-menu bg-primary">
            <ul class="text-light">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'diving:fun-diving' 'dive-snoopy-island' %}"><i
                            class="fas text-info fa-swimmer mr-3"></i>Shore Diving</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'diving:fun-diving' 'fujairah-boat-dive' %}"><i
                            class="fas text-info fa-ship mr-3"></i>Boat
                        Diving</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'diving:padi-course-list' %}"><i
                            class="fas text-info fa-burn mr-3"></i>PADI Courses</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'diving:dive-site-list' %}"><i
                            class="fas text-info fa-map-marked mr-3"></i>Dive Sites</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'diving:prices' %}"><i
                            class="fas text-info fa-money-bill-wave mr-3"></i>Prices</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'core:about-us' %}"><i
                            class="fas text-info fa-calendar-check mr-3"></i>About Us</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'core:contact-us' %}"><i
                            class="fas text-info fa-address-card mr-3"></i>Contact Us</a>
                </li>
            </ul>
        </div>
    </div>

    <nav class="my-navbar navbar navbar-expand-xl">
        <div class="container-fluid">
            <a class="navbar-brand align-content-start" href="{% url 'core:home' %}"><img
                    src="{% static 'core/img/logo.png' %}" alt="Sandy Beach Dive Centre Logo"></a>
            <button class="navbar-toggler" name="navbar-toggler" type="button" id="mobile-menu-btn"><span
                    class="custom-toggler-icon  ml-auto"><i class="fas text-white fa-bars"></i></span></button>
            <div class="collapse navbar-collapse">
                <ul class="navbar-nav ml-auto text-light">
                    <li class="nav-item dropdown">
                        <a data-toggle="dropdown" id="target-dropdown" class="nav-link dropdown-toggle" href="#">Dive
                            With
                            Us</a>
                        <div class="dropdown-menu bg-primary" aria-labelledby="target-dropdown">
                            <a class="nav-link dropdown-item"
                                href="{% url 'diving:fun-diving' 'fujairah-boat-dive' %}">Boat
                                Diving</a>
                            <a class="nav-link dropdown-item"
                                href="{% url 'diving:fun-diving' 'dive-snoopy-island' %}">Shore
                                Diving</a>
                        </div>
                    </li>
                    <!-- <li class="nav-item dropdown">
                        <a data-toggle="dropdown" id="target-dropdown-padi" class="nav-link dropdown-toggle"
                            href="">PADI
                            Courses</a>
                        <div class="dropdown-menu bg-primary" aria-labelledby="target-dropdown-padi">
                            {% for course_level in nav_course_levels %}
                            <a class="nav-link dropdown-item"
                                href="{{ course_level.get_nav_url }}">{{ course_level.title }}</a>
                            {% endfor %}
                        </div>
                    </li> -->
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'diving:padi-course-list' %}">PADI Courses</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'diving:dive-site-list' %}">Dive Sites</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'diving:prices' %}">Prices</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'core:about-us' %}">About Us</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'core:contact-us' %}">Contact Us</a>
                    </li>

                    <!-- {% if current_user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-item nav-link" href="#">Account</a>
                </li>
                <li class="nav-item">
                    <a class="nav-item nav-link" href="#">Logout</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-item nav-link" href="#">Login</a>
                </li>
                {% endif %} -->
                </ul>

            </div>
    </nav>

</header>

core/templates/core/policy.html
{% extends 'layout.html' %}

{% block main %}

    <div class="top-spacer"></div>
    <h1 class="mt-5 text-center">Privacy Policy</h1>

{% endblock %}

core/templates/core/site_map.html
{% extends 'layout.html' %}

{% block main %}

    <div class="top-spacer"></div>
    <h1 class="mt-5 text-center">Site Map</h1>

{% endblock %}

core/templates/core/terms.html
{% extends 'layout.html' %}

{% block main %}

    <div class="top-spacer"></div>
    <h1 class="mt-5 text-center">Terms and Conditions</h1>

{% endblock %}